name: Test Bot on Fork
on:
  # ใช้ pull_request ธรรมดา เพื่อให้มันอ่านไฟล์จาก Branch เราได้เลย
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write # ขอสิทธิ์เขียนคอมเมนต์

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
        run: |
          gh pr comment "$PR_NUMBER" \
            --repo "$REPO" \
            --body "👋 สวัสดีครับคุณ @$ACTOR ! ขอบคุณที่ Contribute นะครับ (Test Bot บน Fork สำเร็จแล้ว! ✅)"