name: Test Bot
on:
  # ใช้ pull_request ธรรมดา เพื่อทดสอบง่ายๆ
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: |
          gh pr comment "${{ github.event.pull_request.html_url }}" \
          --body "👋 สวัสดีครับ! บอททำงานแล้วนะ (Test Success on Fork)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}